### ISSUE TITLE
Watermark: TextLayer

### ISSUE THREAD

**Issue by gerneio** [imazen/imageflow-dotnet-server#15]
In ImageResizer v4 you could have a watermark definition for a text phrase. I'm not seeing this in ImageFlow? Was this feature abandoned? Is there another way to draw text on an image using this library.

**Comment by lilith** [comment]
We do not offer text rasterization in Imageflow.

**Comment by gerneio** [comment]
So if we wanted to implement that layer ourselves, what options do we have? Would we have to process the image after the ImageFlow pipeline has been completed (if possible)?

**Comment by lilith** [comment]
Yes. I would suggest using lossless png as your intermediate format.

**Comment by lilith** [comment]
The best thing to do would be to first render the text to a transparent PNG, then use the watermarking feature to overlay it on top of the image. .AddWatermarkingHandler() allows you to dynamically add watermarks at runtime. 

One way to do this so you don't need temporary files would be to implement IBlobProvider and create a path syntax for generating text. You would then reference those paths from .AddWatermarkingHandler() when supplying the positioning information. 

The reason I suggest doing it with the existing watermarking system is that it will greatly speed up the process. Instead of decoding, encoding, decoding, watermarking, encoding, decoding, re-optimizing (since I'd assume you want Imageflow to optimize the final image file), you would just have `generate text` -> `encode text png` -> `decode source image` -> `decode and overlay watermark` -> `encode and optimize result`.

**Comment by gerneio** [comment]
Thanks for the suggestion Lilith. We may explore going this route sometime down the road.

**Comment by jrnsr8500** [comment]
> The best thing to do would be to first render the text to a transparent PNG, then use the watermarking feature to overlay it on top of the image. .AddWatermarkingHandler() allows you to dynamically add watermarks at runtime.
> 
> One way to do this so you don't need temporary files would be to implement IBlobProvider and create a path syntax for generating text. You would then reference those paths from .AddWatermarkingHandler() when supplying the positioning information.
> 
> The reason I suggest doing it with the existing watermarking system is that it will greatly speed up the process. Instead of decoding, encoding, decoding, watermarking, encoding, decoding, re-optimizing (since I'd assume you want Imageflow to optimize the final image file), you would just have `generate text` -> `encode text png` -> `decode source image` -> `decode and overlay watermark` -> `encode and optimize result`.

Hi, I realize this thread has been closed for some time but I was playing around with your proposed solution above and was wondering what you meant by "create a path syntax for generating text".  Do you have any examples of how you would generate these watermarks in a way that I wouldn't need temporary files?

Thank you!
