### ISSUE TITLE
Error while copying a Website: files in /App_Data/imageflow_hybrid_cache/...metastore are inaccessible

### ISSUE THREAD

**Issue by BeniFreitag** [imazen/imageflow-dotnet-server#68]
We have automated processes to copy an entire web-application, used for testing/staging and upgrade purposes.
Every time we get the following error about a .metastore file:
```
ERROR 32 (0x00000020) Copying File .../App_Data/imageflow_hybrid_cache/db/6/00000046090720481062.metastore
The process cannot access the file because it is being used by another process.
```
How can we solve this?
Is there some file open (unintentionally) left open?
Can we skip these .metastore files or would that have a downside?

**Comment by lilith** [comment]
The .metastore files are the write-ahead-logs, and they remain open until the process ends. If the process is killed they may be left open. 
The cache should not be located inside the web app, and you shouldn't be deploying it.

**Comment by lilith** [comment]
It's important the cache folder never be accessible over http. Putting it
outside the web root solves this issue and others (such as issues with file
change monitors).

It should never be copied or deployed, either.

**Comment by iJungleboy** [comment]
@lilith thanks for these infos

Note that since it's in the `/App_Data/` it's at least not accessible over http. 

Question: If we copy the site to another folder and include the cache folder without the `.metastore` files, will the cached files still be used, or will they be recreated? Because in that case we would of course not copy the cache at all. 

**Moving outside of root not possible**

Placing it outside of the web root is not possible in our case (the CMS DNN) since it would require security reconfiguration. Most DNN installations are hardened that no file access outside of the `/Website/` folder is possible. So making this necessary would be a show stopper. 

What setup do others use, especially other people who include it as a plugin for something which restricts such options as folder placement?

Thanks ;)

**Comment by lilith** [comment]
Definitely don't copy files without the .metastore, they will become
orphaned and never removed.

I would not copy the folder at all.

As long as you are correctly managing file permissions, accessibility, and
the file watcher issues in IIS, it should be fine to use App_Data.

**Comment by iJungleboy** [comment]
thanks. Then let's close this issue ;)

**Comment by BeniFreitag** [comment]
Thanks. We'll skip that folder in the future.
